using DataAccessLayer.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;
using System.Threading.Tasks;

namespace SkillSquare.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    [Authorize(Roles = "Admin")] 
    public class ServiceCategoryController : ControllerBase
    {
        private readonly IServiceCategoryRepository _repo;

        public ServiceCategoryController(IServiceCategoryRepository repo)
        {
            _repo = repo;
        }

        // GET: api/ServiceCategory
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> GetAll()
        {
            var categories = await _repo.GetAllAsync();
            return Ok(categories);
        }

        // GET: api/ServiceCategory/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetById(int id)
        {
            var category = await _repo.GetByIdAsync(id);
            if (category == null) return NotFound("Category not found");
            return Ok(category);
        }

        // POST: api/ServiceCategory
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] ServiceCategoryRequest request)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            // Map DTO to Entity
            var category = new ServiceCategory
            {
                Title = request.Title,
                IconClass = request.IconClass
                // Id is generated by DB automatically
            };

            var result = await _repo.CreateAsync(category);
            if (!result) return BadRequest("Failed to create category");

            return Ok(new { Message = "Category created successfully", CategoryId = category.Id });
        }

        // PUT: api/ServiceCategory/5
        [HttpPut("{id}")]
        public async Task<IActionResult> Update(int id, [FromBody] ServiceCategoryRequest request)
        {
            if (!ModelState.IsValid) return BadRequest(ModelState);

            // 1. Fetch existing category
            var category = await _repo.GetByIdAsync(id);
            if (category == null) return NotFound("Category not found");

            // 2. Update fields
            category.Title = request.Title;
            category.IconClass = request.IconClass;

            // 3. Save changes
            var result = await _repo.UpdateAsync(category);
            if (!result) return BadRequest("Failed to update category");

            return Ok(new { Message = "Category updated successfully" });
        }

        // DELETE: api/ServiceCategory/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _repo.DeleteAsync(id);
            if (!result) return BadRequest("Failed to delete category (it might be in use)");

            return Ok(new { Message = "Category deleted successfully" });
        }
    }
}